# apiVersion: v1
# kind: Service
# metadata:
#   name: snaptrude-kube-service-np
#   labels:
#     name: snaptrude-kube-deploy
#     app: snaptrude-kube-app
# spec:
#   type: NodePort
#   selector:
#     app: snaptrude-kube-app
#   ports:
#     - protocol: TCP
#       port: 6041
#       nodePort: 30072 #3000-32767

apiVersion: v1
kind: Service
metadata:
  name: snaptrude-kube-service-np
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 6041
  selector:
    app: snaptrude-kube-app
